### ISSUE TITLE
Reset OpenWrt config without serial console

### ISSUE THREAD

**Issue by goletsa** [Emeryth/openwrt-zsun#5]
Is it possible?
Flashed openwrt well.
Then configured as AP Clint, AP disapper, can't see device wireless.
And it did not connect to other AP.

**Comment by sehraf** [comment]
from https://wiki.hackerspace.pl/projects:zsun-wifi-card-reader
- Entering failsafe will run a script that automatically does a factory reset
- The SD card detect pin is registered as a button and will trigger failsafe when inserted/removed during boot
- The SD card reader is reset every time a card is inserted or removed"

so yes you should be able to reset by inserting/removing a sd card while booting

**Comment by goletsa** [comment]
Thank your. It work.
